services:
  - type: web
    name: corkytube-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    disk:
      name: corkytube-disk
      mounthPath: /var/data
    autoDeploy: true
    repo: https://github.com/DavorRakic/CorkyTube

  - type: static
    name: corkytube-frontend
    buildCommand: ''
    staticPublishPath: public
    env: static
    plan: free
    repo: https://github.com/DavorRakic/CorkyTube
    autoDeploy: true